<?php
declare(strict_types=1);

namespace SwiftLift;

/**
 * <summary>
 * One-to-one chat tied to an accepted lift request. Handles reading
 * the thread, marking incoming messages read, sending user and system
 * messages, and per-thread unread summaries for the sidebar.
 * </summary>
 * <remarks>
 * Threads only become writable once the underlying lift_request is in
 * the accepted state, so the chat acts as a follow-up channel rather
 * than a way to message strangers. System messages bypass the daily
 * quota and access checks because they are generated by server-side
 * triggers (e.g. "driver moved the pickup pin").
 * </remarks>
 */
final class MessageRepo
{
    /**
     * <summary>
     * Maximum character length of a single message body.
     * </summary>
     */
    public const MAX_BODY      = 280;
    /**
     * <summary>
     * How many user-typed messages one account can send in a rolling
     * 24-hour window. System messages do not count.
     * </summary>
     */
    public const DAILY_LIMIT   = 50;

    /**
     * <summary>
     * Verify the user is part of the named lift request and that the
     * request is currently in the accepted state.
     * </summary>
     * <param name="userId">The viewer.</param>
     * <param name="liftRequestId">The lift_requests row id.</param>
     * <returns>An associative array with from and to user ids for downstream use.</returns>
     * <exception cref="\RuntimeException">If the request is missing, the viewer is not on either side, or the request is not in the accepted state.</exception>
     */
    private static function assertCanAccess(int $userId, int $liftRequestId): array
    {
        $stmt = Db::pdo()->prepare(
            "SELECT lr.id, lr.status, fj.user_id AS from_user, tj.user_id AS to_user
             FROM lift_requests lr
             JOIN journeys fj ON fj.id = lr.from_journey_id
             JOIN journeys tj ON tj.id = lr.to_journey_id
             WHERE lr.id = ?"
        );
        $stmt->execute([$liftRequestId]);
        $row = $stmt->fetch();
        if (!$row) throw new \RuntimeException('Connection not found');

        $from = (int) $row['from_user'];
        $to   = (int) $row['to_user'];
        if ($userId !== $from && $userId !== $to) {
            throw new \RuntimeException('Not part of this connection');
        }
        if ($row['status'] !== 'accepted') {
            throw new \RuntimeException('Messages are only available once a request is accepted');
        }
        return ['from' => $from, 'to' => $to];
    }

    /**
     * <summary>
     * Return the chronological list of messages on a lift-request
     * thread (up to 500) and stamp inbound messages as read on the way
     * out.
     * </summary>
     * <param name="userId">The viewer. Must be one of the two parties on the request.</param>
     * <param name="liftRequestId">The lift_requests row id whose thread to read.</param>
     * <returns>An array of message rows with id, sender_id, body, kind, created_at and read_at.</returns>
     * <exception cref="\RuntimeException">When the access check fails (see assertCanAccess).</exception>
     * <remarks>
     * The read stamp only flips on messages where the viewer is the
     * recipient (sender_id != viewer), so system messages still flip
     * for the non-actor party.
     * </remarks>
     */
    public static function listForLiftRequest(int $userId, int $liftRequestId): array
    {
        self::assertCanAccess($userId, $liftRequestId);

        $pdo  = Db::pdo();
        $stmt = $pdo->prepare(
            "SELECT id, sender_id, body, kind, created_at, read_at
             FROM messages
             WHERE lift_request_id = ?
             ORDER BY created_at ASC, id ASC
             LIMIT 500"
        );
        $stmt->execute([$liftRequestId]);
        $rows = $stmt->fetchAll();

        // Mark inbound messages as read on read. (System messages have the
        // sender's own id but are still inbound to the *other* party, we
        // only flip read_at when the viewer is the recipient, so the same
        // logic works.)
        $pdo->prepare(
            "UPDATE messages
             SET read_at = CURRENT_TIMESTAMP
             WHERE lift_request_id = ? AND sender_id != ? AND read_at IS NULL"
        )->execute([$liftRequestId, $userId]);

        return array_map(static function (array $r): array {
            return [
                'id'         => (int) $r['id'],
                'sender_id'  => (int) $r['sender_id'],
                'body'       => $r['body'],
                'kind'       => $r['kind'] ?? 'user',
                'created_at' => $r['created_at'],
                'read_at'    => $r['read_at'],
            ];
        }, $rows);
    }

    /**
     * <summary>
     * Append a user-typed message to a thread, enforcing the daily
     * quota and length cap.
     * </summary>
     * <param name="userId">The sender. Must be on the lift request.</param>
     * <param name="liftRequestId">The thread to post to.</param>
     * <param name="body">The message body. Trimmed; must be 1..MAX_BODY characters.</param>
     * <returns>The newly stored message row plus a "remaining_today" hint.</returns>
     * <exception cref="\RuntimeException">When access check fails, the body is empty or too long, or the daily quota is exhausted.</exception>
     */
    public static function send(int $userId, int $liftRequestId, string $body): array
    {
        self::assertCanAccess($userId, $liftRequestId);

        $body = trim($body);
        if ($body === '')                              throw new \RuntimeException('Message is empty');
        if (mb_strlen($body) > self::MAX_BODY)         throw new \RuntimeException('Message too long (max ' . self::MAX_BODY . ' characters)');

        $remaining = self::dailyRemaining($userId);
        if ($remaining <= 0) {
            throw new \RuntimeException('Daily message limit reached (' . self::DAILY_LIMIT . '). Try again tomorrow.');
        }

        $pdo  = Db::pdo();
        $ins  = $pdo->prepare(
            "INSERT INTO messages (lift_request_id, sender_id, body) VALUES (?, ?, ?)"
        );
        $ins->execute([$liftRequestId, $userId, $body]);
        $id = (int) $pdo->lastInsertId();

        $stmt = $pdo->prepare("SELECT id, sender_id, body, created_at, read_at FROM messages WHERE id = ?");
        $stmt->execute([$id]);
        $row = $stmt->fetch();
        return [
            'id'         => (int) $row['id'],
            'sender_id'  => (int) $row['sender_id'],
            'body'       => $row['body'],
            'created_at' => $row['created_at'],
            'read_at'    => $row['read_at'],
            'remaining_today' => $remaining - 1,
        ];
    }

    /**
     * <summary>
     * Insert a system-generated message (e.g. "driver moved the pickup
     * pin") into the given thread, bypassing the daily-limit and
     * access checks.
     * </summary>
     * <param name="liftRequestId">The thread to post the notice to.</param>
     * <param name="senderId">The user whose action triggered the notice. The other party on the thread is the effective recipient.</param>
     * <param name="body">The system message body. Trimmed and clamped to MAX_BODY; empty after trimming is a silent no-op.</param>
     * <remarks>
     * The caller (a server-side trigger) is responsible for picking
     * the right thread and sender.
     * </remarks>
     */
    public static function sendSystem(int $liftRequestId, int $senderId, string $body): void
    {
        $body = trim($body);
        if ($body === '') return;
        if (mb_strlen($body) > self::MAX_BODY) {
            $body = mb_substr($body, 0, self::MAX_BODY);
        }
        Db::pdo()->prepare(
            "INSERT INTO messages (lift_request_id, sender_id, body, kind)
             VALUES (?, ?, ?, 'system')"
        )->execute([$liftRequestId, $senderId, $body]);
    }

    /**
     * <summary>
     * How many user-typed messages the user can still send today
     * within the rolling 24-hour window.
     * </summary>
     * <param name="userId">The user whose quota to check.</param>
     * <returns>Messages remaining, clamped at zero.</returns>
     * <remarks>
     * System messages do not count towards the user's quota.
     * </remarks>
     */
    public static function dailyRemaining(int $userId): int
    {
        $stmt = Db::pdo()->prepare(
            "SELECT COUNT(*) FROM messages
             WHERE sender_id = ? AND created_at >= NOW() - INTERVAL 1 DAY"
        );
        $stmt->execute([$userId]);
        $sent = (int) $stmt->fetchColumn();
        return max(0, self::DAILY_LIMIT - $sent);
    }

    /**
     * <summary>
     * Per-connection unread count keyed by lift_request_id, plus the
     * most recent message preview. Used to badge connections in the
     * sidebar.
     * </summary>
     * <param name="userId">The viewer.</param>
     * <returns>An associative array keyed by lift_request_id, each value containing unread (int), last_at (timestamp string), last_body (string), last_sender (?int).</returns>
     */
    public static function summaryForUser(int $userId): array
    {
        $sql = "
            SELECT lr.id AS lift_request_id,
                   SUM(CASE WHEN m.sender_id != :uid AND m.read_at IS NULL THEN 1 ELSE 0 END) AS unread,
                   MAX(m.created_at) AS last_at,
                   (SELECT body  FROM messages m2
                    WHERE m2.lift_request_id = lr.id
                    ORDER BY m2.created_at DESC, m2.id DESC LIMIT 1) AS last_body,
                   (SELECT sender_id FROM messages m2
                    WHERE m2.lift_request_id = lr.id
                    ORDER BY m2.created_at DESC, m2.id DESC LIMIT 1) AS last_sender
            FROM lift_requests lr
            JOIN journeys fj ON fj.id = lr.from_journey_id
            JOIN journeys tj ON tj.id = lr.to_journey_id
            LEFT JOIN messages m ON m.lift_request_id = lr.id
            WHERE lr.status = 'accepted'
              AND (fj.user_id = :uid_from OR tj.user_id = :uid_to)
            GROUP BY lr.id";

        $stmt = Db::pdo()->prepare($sql);
        $stmt->execute([':uid' => $userId, ':uid_from' => $userId, ':uid_to' => $userId]);
        $out = [];
        foreach ($stmt->fetchAll() as $r) {
            $out[(int) $r['lift_request_id']] = [
                'unread'      => (int) $r['unread'],
                'last_at'     => $r['last_at'],
                'last_body'   => $r['last_body'],
                'last_sender' => $r['last_sender'] === null ? null : (int) $r['last_sender'],
            ];
        }
        return $out;
    }
}
